// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function Make(Config) {
  var getInitialState = Config[0];
  var reducer = Config[1];
  var state = /* record */[/* contents */Curry._1(getInitialState, /* () */0)];
  var listeners = /* record */[/* contents : [] */0];
  var dispatch = function (action) {
    state[0] = Curry._2(reducer, state[0], action);
    return List.iter((function (listener) {
                  return Curry._1(listener, /* () */0);
                }), listeners[0]);
  };
  var getState = function (param) {
    return state[0];
  };
  var subscribe = function (fn) {
    listeners[0] = /* :: */[
      fn,
      listeners[0]
    ];
    return (function (param) {
        listeners[0] = List.filter((function (l) {
                  return l !== fn;
                }))(listeners[0]);
        return /* () */0;
      });
  };
  var useMappedState = function (mapper) {
    var match = React.useState((function () {
            return Curry._1(mapper, state[0]);
          }));
    var setSyncedState = match[1];
    React.useEffect((function () {
            return subscribe((function (param) {
                          return Curry._1(setSyncedState, (function (param) {
                                        return Curry._1(mapper, state[0]);
                                      }));
                        }));
          }));
    return match[0];
  };
  var useState = function (param) {
    return useMappedState((function (state) {
                  return state;
                }));
  };
  var make = function (mapper, children) {
    var state = useMappedState(mapper);
    return /* :: */[
            Curry._1(children, state),
            /* [] */0
          ];
  };
  var Consumer = /* module */[/* make */make];
  return /* module */[
          /* getInitialState */getInitialState,
          /* reducer */reducer,
          /* state */state,
          /* listeners */listeners,
          /* dispatch */dispatch,
          /* getState */getState,
          /* subscribe */subscribe,
          /* useMappedState */useMappedState,
          /* useState */useState,
          /* Consumer */Consumer
        ];
}

exports.Make = Make;
/* react Not a pure module */
